[package]
name = "sqrprob"
version = "0.1.0"
authors = ["Ezra Dudden <ezradudden@gmail.com>"]

[dependencies]
rand = "0.7.3"
threadpool = "1.8.1"
easy-http-request = "0.2.6"

[profile.release]
debug = true
